{
 "title": "Kafka Streams App Monitoring: Stock Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Health View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Num of Kafka Streams Instances Active",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(up{job=\"kafka-streams\"})",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "Streams Fetch Calls Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{client_id!~\"(.+)-restore-consumer\"}",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "Task Creation vs Task Closing Rate ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_task_created_rate",
       "legendFormat": "{{instance}}-{{job}}"
      },
      {
       "expr": "kafka_streams_stream_thread_metrics_task_closed_rate",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "Bytes Consumed Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{client_id!~\"(.+)-restore-consumer\",topic!=\"\"}",
       "legendFormat": "{{instance}}-{{job}}-{{topic}}"
      }
     ]
    },
    {
     "title": "Messages Consumed Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{client_id!~\"(.+)-restore-consumer\",topic!=\"\"}",
       "legendFormat": "{{instance}}-{{job}}-{{topic}}"
      }
     ]
    },
    {
     "title": "Max Consumer Lag per Instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{client_id!~\"(.+)-restore-consumer\",topic!=\"\"}",
       "legendFormat": "{{instance}}-{{job}}-{{topic}}-{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Streams App Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg Poll Time Per Thread (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "Max Poll Time Per Thread (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_max",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "Poll Time Per Thread Per Second (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_rate",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "Avg Processing Time Per Thread (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_avg",
       "legendFormat": "{{instance}}-{{job}}-{{thread_id}}"
      }
     ]
    },
    {
     "title": "Max Processing Time Per Thread (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_max",
       "legendFormat": "{{instance}}-{{job}}-{{thread_id}}"
      }
     ]
    },
    {
     "title": "Processing Time Per Thread Per Second (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_rate",
       "legendFormat": "{{instance}}-{{job}}-{{thread_id}}"
      }
     ]
    },
    {
     "title": "Average Commit Time Per Thread (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg",
       "legendFormat": "{{instance}}-{{job}}-{{thread_id}}"
      }
     ]
    },
    {
     "title": "Max Commit Time Per Thread (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_max",
       "legendFormat": "{{instance}}-{{job}}-{{thread_id}}"
      }
     ]
    },
    {
     "title": "Commit Time Per Thread Per Second (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_rate",
       "legendFormat": "{{instance}}-{{job}}-{{thread_id}}"
      }
     ]
    },
    {
     "title": "Avg Punctuation Time Per Thread (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_avg",
       "legendFormat": "{{instance}}-{{job}}-{{thread_id}}"
      }
     ]
    },
    {
     "title": "Max Punctuation Time Per Thread (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_max",
       "legendFormat": "{{instance}}-{{job}}-{{thread_id}}"
      }
     ]
    },
    {
     "title": "Punctuation Time Per Thread Per Second (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_rate",
       "legendFormat": "{{instance}}-{{job}}-{{thread_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM and System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC Time Rate [1m] [seconds]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "percent", "label": "% of time in GC" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_count{job=\"kafka-streams\"}[1m]))",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 108 },
     "yaxes": [
      { "format": "percent", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka-streams\"}[1m])",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 108 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka-streams\"})",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of MemTables Per Task",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_size_all_mem_tables",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Cache Usage Per Task",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_usage",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Cache Pinned Usage Per Task",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_pinned_usage",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Estimate Table Readers Mem Per Task",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_estimate_table_readers_mem",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Size On Disk Per Task",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_total_sst_files_size",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memtable Flush Rate Per Task",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_bytes_flushed_rate",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memtable Total Bytes Flushed Per Task",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_bytes_flushed_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes Read Compation Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_read_compaction_rate",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes Written Compaction Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_written_compaction_rate",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write Stall Duration Avg",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_write_stall_duration_avg",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write Stall Duration Total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 37 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_write_stall_duration_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MemTable Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 37 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_hit_ratio",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Cache Data Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_data_hit_ratio",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Cache Filter Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 49 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_filter_hit_ratio",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Cache Index Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 49 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_index_hit_ratio",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Open Files",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_number_open_files",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}