apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  serviceName: grafana
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          volumeMounts:
            - name: config-volume
              mountPath: /etc/grafana/provisioning/datasources
          ports:
            - containerPort: 3000
      volumes:
        - name: config-volume
          configMap:
            name: grafana-server-config
---
kind: Service
apiVersion: v1
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - name: grafanaui
      protocol: TCP
      port: 3000
      targetPort: 3000
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: grafana-server-config
    labels:
      name: grafana-server-config
    namespace: default
  data:
    datasource.yml: |-
      # config file version
      apiVersion: 1

      # list of datasources that should be deleted from the database
      deleteDatasources:
        - name: Prometheus
          orgId: 1

      # list of datasources to insert/update depending
      # whats available in the database
      datasources:
        # <string, required> name of the datasource. Required
      - name: Prometheus
        # <string, required> datasource type. Required
        type: prometheus
        # <string, required> access mode. direct or proxy. Required
        access: proxy
        # <int> org id. will default to orgId 1 if not specified
        orgId: 1
        # <string> url
        url: http://prometheus-service:9090
