apiVersion: apps/v1
kind: Deployment
metadata:
  name: lag-exporter
  labels:
    app: lag-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lag-exporter
  template:
    metadata:
      labels:
        app: lag-exporter
    spec:
      containers:
        - name: prometheus
          image: lightbend/kafka-lag-exporter:0.6.2
          volumeMounts:
            - name: config-volume
              mountPath: /opt/docker/conf/
          ports:
            - containerPort: 9090
      volumes:
        - name: config-volume
          secret:
            secretName: lag-exporter-config
---
kind: Service
apiVersion: v1
metadata:
  name: lag-exporter-service
spec:
  selector:
    app: lag-exporter
  ports:
    - name: exporter
      protocol: TCP
      port: 9999
      targetPort: 9999
    - name: prom-exporter
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Secret
metadata:
  name: lag-exporter-config
  labels:
    name: lag-exporter-config
  namespace: default
data:
  application.conf: |-
    a2Fma2EtbGFnLWV4cG9ydGVyIHsKICBwb3J0ID0gOTk5OQoKICBjbGllbnQtZ3JvdXAtaWQgPSAic3RvY2tzdGF0LTIiCiAgbG9va3VwLXRhYmxlLXNpemUgPSAxMjAKCiAgY2x1c3RlcnMgPSBbCiAgICB7CiAgICAgIG5hbWUgPSAiY2Nsb3VkLWF6dXJlIgogICAgICBib290c3RyYXAtYnJva2VycyA9ICJwa2MtbGd3Z20uZWFzdHVzMi5henVyZS5jb25mbHVlbnQuY2xvdWQ6OTA5MiIKCiAgICAgIGFkbWluLWNsaWVudC1wcm9wZXJ0aWVzID0gewogICAgICAgIGNsaWVudC5pZCA9ICJleHBvcnRlci1hZG1pbiIKICAgICAgICBzZWN1cml0eS5wcm90b2NvbCA9ICJTQVNMX1NTTCIKICAgICAgICBzYXNsLm1lY2hhbmlzbSA9ICJQTEFJTiIKICAgICAgICBzYXNsLmphYXMuY29uZmlnID0gIm9yZy5hcGFjaGUua2Fma2EuY29tbW9uLnNlY3VyaXR5LnBsYWluLlBsYWluTG9naW5Nb2R1bGUgcmVxdWlyZWQgdXNlcm5hbWU9XCJKRlkyV1ZXN0U0UkQ3TjZVXCIgcGFzc3dvcmQ9XCI5aVVXaUx2Q200dTZpZndpSEQ4MndTOWtiYlBSZDhtQlA2d1NhajlwdFZHczVYZHZ3UkhDa1RtM1FaSFNsTkJtXCI7IgogICAgICB9CgogICAgICBjb25zdW1lci1wcm9wZXJ0aWVzID0gewogICAgICAgIGNsaWVudC5pZCA9ICJleHBvcnRlci1jb25zdW1lciIKICAgICAgICBzZWN1cml0eS5wcm90b2NvbCA9ICJTQVNMX1NTTCIKICAgICAgICBzYXNsLm1lY2hhbmlzbSA9ICJQTEFJTiIKICAgICAgICBzYXNsLmphYXMuY29uZmlnID0gIm9yZy5hcGFjaGUua2Fma2EuY29tbW9uLnNlY3VyaXR5LnBsYWluLlBsYWluTG9naW5Nb2R1bGUgcmVxdWlyZWQgdXNlcm5hbWU9XCJKRlkyV1ZXN0U0UkQ3TjZVXCIgcGFzc3dvcmQ9XCI5aVVXaUx2Q200dTZpZndpSEQ4MndTOWtiYlBSZDhtQlA2d1NhajlwdFZHczVYZHZ3UkhDa1RtM1FaSFNsTkJtXCI7IgogICAgICB9CiAgICB9CiAgXQp9Cg==